spring.application.name=jwt-security

# PostgreSQL configurations
#REPLACE THIS WITH YOUR DATABASE CREDENTIALS
#spring.datasource.url=jdbc:postgresql://localhost:5432/jwt_security 
#spring.datasource.username=postgres
#spring.datasource.password=1234
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/auth_product_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:app_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:secure_password_123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# JPA/Hibernate properties
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
app.jwt.secret=3c9c3524b5e7d5904d9c3524b5e7d5904d9c3524b5e7d5904d9c3524b5e7d590
app.jwt.expiration=3600000
app.jwt.refresh-expiration=86400000
